/* ============================================================
   roadmaps.js — goal-specific roadmap templates + registry
   Each goal provides { phases, milestones, resources }.
   setActiveRoadmap() swaps the active PHASES/MILESTONES/
   RESOURCES/TRACKER (declared in data.js) for the chosen goal.
   ============================================================ */

// compact builders
const ph = (id, months, title, goal, outcome, certs, plan) => ({ id, months, title, goal, outcome, certs, plan });
const mo = (n, title, study, hands, deliverable) => ({ n, title, study, hands, deliverable });
const ms = (time, sub, icon, role, title, items) => ({ time, sub, icon, role, title, items });
const rs = (ico, title, items) => ({ ico, title, items });

/* ===================== AI ENGINEER ===================== */
const AI_ENGINEER = {
  phases: [
    ph("p1", "Months 1–3", "ML Foundations", "Python, math & classic ML",
      "Build the mathematical and programming base of machine learning and ship your first trained models.",
      ["(optional) ML foundations"],
      [
        mo(1, "Python & Data Tooling",
          ["Python, NumPy, pandas, Jupyter", "Data cleaning & manipulation", "Git & virtual environments"],
          ["Load, clean and explore a real dataset", "Plot distributions & correlations", "Push an EDA notebook to GitHub"],
          "Exploratory data analysis notebook with insights"),
        mo(2, "Math for ML",
          ["Linear algebra & vectors", "Probability & statistics", "Gradient descent intuition"],
          ["Implement linear regression from scratch", "Code gradient descent", "Visualize the loss surface"],
          "From-scratch linear regression notebook"),
        mo(3, "Classic ML with scikit-learn",
          ["Regression, classification, clustering", "Train/test split, cross-validation", "Feature engineering & metrics"],
          ["Train & compare 3 models", "Tune hyperparameters", "Evaluate with proper metrics"],
          "ML project with model comparison + README"),
      ]),
    ph("p2", "Months 4–6", "Deep Learning", "Neural nets, CV & NLP",
      "Master deep learning with PyTorch/TensorFlow across vision and language.",
      ["TensorFlow Developer (optional)"],
      [
        mo(4, "Neural Networks",
          ["PyTorch/TensorFlow basics", "Backprop, activations, optimizers", "Training loops & regularization"],
          ["Build an MLP on MNIST", "Track training curves", "Fix overfitting"],
          "Digit classifier with training report"),
        mo(5, "Computer Vision",
          ["CNNs & convolutions", "Transfer learning", "Data augmentation"],
          ["Fine-tune a pretrained ResNet", "Build an image pipeline", "Evaluate on a custom dataset"],
          "Image classification app"),
        mo(6, "NLP & Transformers",
          ["Embeddings & tokenization", "Attention & transformers", "Hugging Face Transformers"],
          ["Fine-tune a transformer", "Build a text classifier", "Analyze errors"],
          "Sentiment / text-classification model"),
      ]),
    ph("p3", "Months 7–9", "LLMs & MLOps", "RAG, fine-tuning & serving",
      "Work with large language models and learn to ship models reliably.",
      ["Azure AI-102 or AWS ML (optional)"],
      [
        mo(7, "LLMs & RAG",
          ["Prompting & context windows", "Embeddings & vector databases", "LangChain / orchestration"],
          ["Build a RAG chatbot over your docs", "Add citations & guardrails", "Evaluate answer quality"],
          "Retrieval-augmented chatbot"),
        mo(8, "Fine-tuning & Evaluation",
          ["LoRA / PEFT fine-tuning", "Evaluation & benchmarks", "Safety & guardrails"],
          ["Fine-tune a small LLM", "Build an eval harness", "Compare base vs tuned"],
          "Fine-tuned model + evaluation report"),
        mo(9, "MLOps",
          ["Experiment tracking (MLflow/W&B)", "Docker + FastAPI serving", "CI/CD for ML"],
          ["Containerize a model API", "Add tracking & versioning", "Automate deploy"],
          "Deployed inference API with tracking"),
      ]),
    ph("p4", "Months 10–12", "Production AI & Capstone", "Scale, safety & portfolio",
      "Serve AI at scale responsibly and prove it with a capstone.",
      ["🤖 AI Engineer job-ready"],
      [
        mo(10, "Scaling & Serving",
          ["GPU inference, batching, vLLM", "Monitoring & cost control", "Caching & latency"],
          ["Build scalable serving", "Add monitoring & alerts", "Load-test the service"],
          "Monitored, scalable model service"),
        mo(11, "Data & Responsible AI",
          ["Data & feature pipelines", "Bias, fairness & safety", "Feature stores"],
          ["Build a data pipeline", "Run a bias/safety review", "Document model card"],
          "End-to-end pipeline + model card"),
        mo(12, "Capstone & Interview",
          ["System design for ML", "Portfolio storytelling", "ML interview prep"],
          ["Ship a full AI product", "Write architecture + README", "Practice ML interviews"],
          "Capstone AI product + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundations", "🌱", "ML Aware", "ML foundations locked in",
      ["Python + pandas fluency", "Math for ML understood", "3 classic-ML models trained", "EDA + ML notebooks on GitHub"]),
    ms("6 Months", "Deep Learning", "🧠", "Junior ML Engineer", "Deep learning across CV & NLP",
      ["Neural nets in PyTorch/TF", "CV transfer-learning app", "NLP transformer model", "2+ DL projects"]),
    ms("9 Months", "LLM + MLOps", "🚀", "AI Engineer", "LLMs shipped reliably",
      ["RAG chatbot built", "Fine-tuned & evaluated a model", "Model served via API", "MLOps basics mastered"]),
    ms("12 Months", "Production", "🤖", "AI Engineer", "Production AI + capstone",
      ["Scalable, monitored serving", "Responsible-AI review done", "Capstone product shipped", "Interviewing for AI roles"]),
  ],
  resources: [
    rs("📚", "Courses", ["DeepLearning.AI", "fast.ai", "Andrew Ng ML", "Hugging Face course"]),
    rs("🧪", "Practice", ["Kaggle", "Google Colab", "Papers with Code", "Hugging Face Hub"]),
    rs("🛠️", "Tools", ["PyTorch / TensorFlow", "scikit-learn", "LangChain / LlamaIndex", "MLflow / W&B"]),
    rs("🧠", "LLMs", ["OpenAI / Azure OpenAI", "Ollama (local)", "Vector DBs (pgvector/Pinecone)", "Prompt engineering guide"]),
    rs("📖", "Theory", ["3Blue1Brown (math)", "Deep Learning book", "Distill.pub", "arXiv"]),
    rs("🚀", "MLOps", ["Docker", "FastAPI", "MLOps Zoomcamp", "Made With ML"]),
  ],
};

/* ===================== DEVOPS ENGINEER ===================== */
const DEVOPS_ENGINEER = {
  phases: [
    ph("p1", "Months 1–3", "Foundations", "Linux, networking & code",
      "Master the fundamentals every DevOps engineer relies on daily.",
      ["Linux Essentials (optional)"],
      [
        mo(1, "Linux & Shell",
          ["Linux filesystem & permissions", "Bash scripting", "Processes, systemd, cron"],
          ["Automate tasks with Bash", "Manage services & logs", "Write a backup script"],
          "Bash automation toolkit repo"),
        mo(2, "Networking & Git",
          ["TCP/IP, DNS, HTTP, TLS", "Load balancing & proxies", "Git branching & PRs"],
          ["Diagnose with curl/dig/netstat", "Set up nginx reverse proxy", "Practice Git workflows"],
          "Networking lab notes + nginx config"),
        mo(3, "Programming & IaC intro",
          ["Python or Go basics", "YAML & config", "Infrastructure as Code concepts"],
          ["Write a CLI tool", "Parse & template configs", "Provision a VM by script"],
          "Small automation CLI + provisioning script"),
      ]),
    ph("p2", "Months 4–6", "Containers & CI/CD", "Docker, pipelines, Kubernetes",
      "Package, automate, and orchestrate applications.",
      ["Docker / GitHub Actions"],
      [
        mo(4, "Docker",
          ["Images, layers, registries", "Multi-stage builds", "Docker Compose"],
          ["Containerize an app", "Optimize image size", "Compose a multi-service stack"],
          "Dockerized multi-service app"),
        mo(5, "CI/CD",
          ["Pipelines & stages", "GitHub Actions / GitLab CI", "Testing & artifacts"],
          ["Build a build→test→deploy pipeline", "Add caching & secrets", "Publish artifacts"],
          "End-to-end CI/CD pipeline"),
        mo(6, "Kubernetes",
          ["Pods, deployments, services", "ConfigMaps, secrets, ingress", "Helm basics"],
          ["Deploy to a local cluster", "Expose via ingress", "Package with Helm"],
          "App deployed on Kubernetes + Helm chart"),
      ]),
    ph("p3", "Months 7–9", "Cloud & IaC", "Terraform, cloud, config mgmt",
      "Provision and manage cloud infrastructure as code.",
      ["Terraform Associate", "AWS/Azure Associate"],
      [
        mo(7, "Cloud Core",
          ["Compute, storage, networking", "IAM & security", "Managed Kubernetes (EKS/AKS/GKE)"],
          ["Deploy to managed K8s", "Set up IAM roles", "Configure cloud networking"],
          "Cloud-hosted app with least-privilege IAM"),
        mo(8, "Terraform",
          ["HCL, providers, state", "Modules & workspaces", "Remote state & plan/apply"],
          ["Provision infra with Terraform", "Build reusable modules", "Manage remote state"],
          "Terraform module repo"),
        mo(9, "Config Mgmt & GitOps",
          ["Ansible", "Helm advanced", "GitOps (Argo CD / Flux)"],
          ["Configure servers with Ansible", "Set up GitOps deploys", "Automate rollouts"],
          "GitOps-driven deployment"),
      ]),
    ph("p4", "Months 10–12", "SRE & Capstone", "Observability, security, platform",
      "Operate reliable systems and prove it with a platform capstone.",
      ["⚙️ DevOps Engineer job-ready", "CKA (optional)"],
      [
        mo(10, "Observability",
          ["Prometheus & Grafana", "Centralized logging (Loki/ELK)", "Alerting & SLOs"],
          ["Instrument metrics & dashboards", "Ship logs centrally", "Define SLOs + alerts"],
          "Full observability stack"),
        mo(11, "DevSecOps & Reliability",
          ["Secrets management (Vault)", "Scanning & policy-as-code", "Incident response & chaos"],
          ["Add security scanning to CI", "Manage secrets securely", "Run a failure drill"],
          "Hardened, secure pipeline + runbook"),
        mo(12, "Capstone & Interview",
          ["Platform architecture", "Cost & scaling", "DevOps interview prep"],
          ["Build an internal platform", "Document architecture", "Practice interviews"],
          "Capstone platform + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundations", "🌱", "DevOps Aware", "Linux, networking & scripting",
      ["Bash automation fluency", "Networking & Git mastered", "First IaC scripts", "Automation repo live"]),
    ms("6 Months", "Containers", "📦", "Junior DevOps", "Docker, CI/CD & Kubernetes",
      ["Apps containerized", "CI/CD pipeline shipped", "K8s deployment + Helm", "2+ projects"]),
    ms("9 Months", "Cloud & IaC", "☁️", "DevOps Engineer", "Cloud infra as code",
      ["Terraform modules", "Managed K8s in cloud", "GitOps deploys", "Config mgmt with Ansible"]),
    ms("12 Months", "SRE", "⚙️", "DevOps Engineer", "Reliable platform + capstone",
      ["Observability stack", "DevSecOps pipeline", "Capstone platform", "Interviewing for DevOps roles"]),
  ],
  resources: [
    rs("📚", "Learn", ["KodeKloud", "DevOps Roadmap (roadmap.sh)", "Linux Journey", "The Twelve-Factor App"]),
    rs("🧪", "Practice", ["Play with Docker", "Katacoda/killercoda", "AWS/Azure free tier", "GitHub Actions"]),
    rs("🛠️", "Tools", ["Docker & Kubernetes", "Terraform", "Ansible", "Argo CD / Helm"]),
    rs("📈", "Observability", ["Prometheus", "Grafana", "Loki / ELK", "OpenTelemetry"]),
    rs("🔐", "Security", ["HashiCorp Vault", "Trivy / Snyk", "OPA / policy-as-code", "OWASP"]),
    rs("🎓", "Certs", ["CKA / CKAD", "Terraform Associate", "AWS DevOps Pro", "Azure DevOps"]),
  ],
};

/* ===================== DATA ENGINEER ===================== */
const DATA_ENGINEER = {
  phases: [
    ph("p1", "Months 1–3", "Foundations", "SQL, Python & modeling",
      "Build the querying, programming, and modeling core of data engineering.",
      ["(optional) SQL / Python cert"],
      [
        mo(1, "SQL Mastery",
          ["Joins, aggregation, window functions", "Query optimization & indexes", "Schema design"],
          ["Solve advanced SQL problems", "Optimize slow queries", "Design a normalized schema"],
          "SQL query portfolio"),
        mo(2, "Python for Data",
          ["pandas & data wrangling", "APIs & file formats (CSV/JSON/Parquet)", "Automation & scheduling"],
          ["Build an ingestion script", "Clean & transform data", "Schedule a job"],
          "Python ETL script"),
        mo(3, "Data Modeling & Warehousing",
          ["OLTP vs OLAP", "Star/snowflake schemas", "Dimensional modeling"],
          ["Model a data warehouse", "Design fact/dim tables", "Document the model"],
          "Dimensional model + docs"),
      ]),
    ph("p2", "Months 4–6", "Pipelines & Big Data", "Airflow, Spark, warehouse",
      "Move and process data at scale with modern tooling.",
      ["Cloud data cert (DP-203/GCP/AWS)"],
      [
        mo(4, "ETL/ELT & Orchestration",
          ["Batch pipelines", "Apache Airflow DAGs", "Idempotency & retries"],
          ["Build an Airflow DAG", "Orchestrate a pipeline", "Handle failures"],
          "Orchestrated ETL pipeline"),
        mo(5, "Apache Spark",
          ["Spark architecture & RDD/DataFrame", "Transformations & actions", "Partitioning & performance"],
          ["Process big data with Spark", "Tune a slow job", "Write to a warehouse"],
          "Spark batch job"),
        mo(6, "Cloud Data Warehouse",
          ["BigQuery / Snowflake / Redshift", "Loading & partitioning", "Cost & performance"],
          ["Load data into a warehouse", "Partition & cluster tables", "Optimize query cost"],
          "Warehouse with optimized tables"),
      ]),
    ph("p3", "Months 7–9", "Streaming & Lakehouse", "Kafka, dbt, lakehouse",
      "Handle real-time data and modern transformation workflows.",
      ["dbt / streaming (optional)"],
      [
        mo(7, "Streaming",
          ["Kafka topics & partitions", "Producers/consumers", "Stream processing"],
          ["Build a streaming pipeline", "Process events in real time", "Handle backpressure"],
          "Real-time streaming pipeline"),
        mo(8, "dbt & Transformations",
          ["dbt models & tests", "Incremental models", "Documentation & lineage"],
          ["Build dbt models", "Add tests & docs", "Set up CI for dbt"],
          "dbt project with tests"),
        mo(9, "Data Lake / Lakehouse",
          ["Data lake vs lakehouse", "Delta / Iceberg", "Medallion architecture"],
          ["Build a lakehouse layer", "Implement bronze/silver/gold", "Query the lake"],
          "Lakehouse pipeline"),
      ]),
    ph("p4", "Months 10–12", "Scale & Capstone", "Governance, quality, portfolio",
      "Operate trustworthy data platforms and ship a capstone.",
      ["🗄️ Data Engineer job-ready"],
      [
        mo(10, "Performance & Cost",
          ["Partitioning & bucketing", "Caching & materialization", "Cost optimization"],
          ["Tune pipeline performance", "Cut warehouse cost", "Benchmark improvements"],
          "Performance + cost report"),
        mo(11, "Quality & Governance",
          ["Data quality & tests", "Governance & lineage", "CI/CD for data"],
          ["Add data quality checks", "Track lineage", "Automate deployments"],
          "Governed, tested pipeline"),
        mo(12, "Capstone & Interview",
          ["End-to-end architecture", "Data system design", "DE interview prep"],
          ["Build an end-to-end platform", "Document architecture", "Practice interviews"],
          "Capstone data platform + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundations", "🌱", "Data Aware", "SQL, Python & modeling",
      ["Advanced SQL fluency", "Python ETL scripting", "Dimensional modeling", "SQL portfolio live"]),
    ms("6 Months", "Pipelines", "🔧", "Junior Data Engineer", "Airflow, Spark & warehouse",
      ["Airflow pipelines", "Spark batch jobs", "Cloud warehouse loaded", "2+ projects"]),
    ms("9 Months", "Streaming", "🌊", "Data Engineer", "Real-time & lakehouse",
      ["Kafka streaming pipeline", "dbt models + tests", "Lakehouse architecture", "Orchestration mastered"]),
    ms("12 Months", "Scale", "🗄️", "Data Engineer", "Governed platform + capstone",
      ["Performance & cost tuned", "Data quality + governance", "Capstone platform", "Interviewing for DE roles"]),
  ],
  resources: [
    rs("📚", "Learn", ["Data Engineering Zoomcamp", "roadmap.sh/data-engineer", "Designing Data-Intensive Apps", "Mode SQL tutorial"]),
    rs("🧪", "Practice", ["Kaggle datasets", "dbt Learn", "Databricks Community", "LeetCode SQL"]),
    rs("🛠️", "Tools", ["Airflow", "Apache Spark", "dbt", "Kafka"]),
    rs("🏢", "Warehouses", ["BigQuery", "Snowflake", "Redshift", "Databricks / Delta"]),
    rs("🔎", "Quality", ["Great Expectations", "dbt tests", "OpenLineage", "Data contracts"]),
    rs("🎓", "Certs", ["Azure DP-203", "GCP Data Engineer", "AWS Data Analytics", "Databricks"]),
  ],
};

/* ===================== CYBERSECURITY ENGINEER ===================== */
const CYBER_ENGINEER = {
  phases: [
    ph("p1", "Months 1–3", "Foundations", "Networking, OS & security basics",
      "Build the networking, systems, and security fundamentals of the field.",
      ["CompTIA Security+ (begin)"],
      [
        mo(1, "Networking",
          ["TCP/IP, DNS, HTTP/S", "Firewalls, VPN, ports", "Packet analysis (Wireshark)"],
          ["Analyze traffic in Wireshark", "Map a network", "Configure firewall rules"],
          "Network analysis lab notes"),
        mo(2, "OS & Hardening",
          ["Linux & Windows security", "Users, permissions, logging", "System hardening"],
          ["Harden a Linux server", "Audit accounts & logs", "Apply CIS benchmarks"],
          "Hardening checklist + evidence"),
        mo(3, "Security Fundamentals",
          ["CIA triad & threat models", "Cryptography basics", "Authentication & access control"],
          ["Encrypt/verify with tools", "Model threats for an app", "Set up MFA"],
          "Threat model + crypto lab"),
      ]),
    ph("p2", "Months 4–6", "Threats & AppSec", "Vulnerabilities, OWASP, defense",
      "Understand attacks and secure applications and networks.",
      ["Security+ (pass)"],
      [
        mo(4, "Threats & Vulnerabilities",
          ["Malware, phishing, attacks", "Vulnerability scanning", "CVEs & patching"],
          ["Scan with Nessus/OpenVAS", "Triage vulnerabilities", "Plan remediation"],
          "Vulnerability assessment report"),
        mo(5, "Web App Security",
          ["OWASP Top 10", "Injection, XSS, auth flaws", "Secure coding basics"],
          ["Exploit a deliberately vulnerable app", "Fix the vulnerabilities", "Use Burp Suite"],
          "Web pentest + fixes writeup"),
        mo(6, "Network Defense",
          ["Segmentation & hardening", "IDS/IPS", "Secure architecture"],
          ["Deploy an IDS (Suricata/Snort)", "Segment a lab network", "Detect an attack"],
          "Defended network lab"),
      ]),
    ph("p3", "Months 7–9", "Blue/Red & Cloud", "SIEM, pentest, cloud security",
      "Operate detection tooling and secure cloud environments.",
      ["CySA+ / SC-200 (optional)"],
      [
        mo(7, "SIEM & Monitoring",
          ["Log collection & SIEM", "Detection rules", "Threat hunting"],
          ["Set up a SIEM (Splunk/ELK)", "Write detection rules", "Hunt for threats"],
          "SIEM dashboards + detections"),
        mo(8, "Pentesting Basics",
          ["Recon & enumeration", "Exploitation & privilege escalation", "Reporting"],
          ["Complete guided pentest labs", "Escalate privileges", "Write a pentest report"],
          "Pentest report (lab)"),
        mo(9, "Cloud Security",
          ["Cloud IAM & config", "CSPM & posture", "Secrets & encryption"],
          ["Audit cloud IAM", "Fix misconfigurations", "Enable posture management"],
          "Cloud security audit + fixes"),
      ]),
    ph("p4", "Months 10–12", "IR, GRC & Capstone", "Response, compliance, portfolio",
      "Respond to incidents, understand governance, and ship a capstone.",
      ["🛡️ Cybersecurity Engineer job-ready"],
      [
        mo(10, "Incident Response",
          ["IR lifecycle", "Digital forensics basics", "Containment & recovery"],
          ["Run a tabletop IR exercise", "Analyze an incident", "Write an IR report"],
          "Incident response runbook"),
        mo(11, "GRC & Compliance",
          ["Frameworks (NIST, ISO 27001)", "Risk management", "Policies & audits"],
          ["Map controls to a framework", "Perform a risk assessment", "Draft security policy"],
          "Risk assessment + policy set"),
        mo(12, "Capstone & Interview",
          ["Secure architecture", "Blue/red teaming", "Security interview prep"],
          ["Build a secured lab environment", "Document defenses", "Practice interviews"],
          "Capstone secure lab + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundations", "🌱", "Security Aware", "Networking, OS & basics",
      ["Traffic analysis skills", "Hardened systems", "Threat modeling", "Security+ prep underway"]),
    ms("6 Months", "AppSec", "🐛", "Junior Security Eng", "Threats, OWASP & defense",
      ["🎓 Security+ passed", "Vulnerability assessment", "Web pentest + fixes", "Network defense lab"]),
    ms("9 Months", "Blue/Red", "🔍", "Cybersecurity Engineer", "SIEM, pentest & cloud",
      ["SIEM detections built", "Pentest report (lab)", "Cloud security audit", "Threat hunting"]),
    ms("12 Months", "IR & GRC", "🛡️", "Cybersecurity Engineer", "Response + capstone",
      ["IR runbook + forensics", "Risk assessment + policy", "Capstone secure lab", "Interviewing for security roles"]),
  ],
  resources: [
    rs("📚", "Learn", ["TryHackMe", "Hack The Box Academy", "Professor Messer (Security+)", "roadmap.sh/cyber-security"]),
    rs("🧪", "Practice", ["TryHackMe rooms", "HTB labs", "OverTheWire", "PortSwigger Web Security"]),
    rs("🛠️", "Tools", ["Wireshark", "Burp Suite", "Nmap", "Metasploit"]),
    rs("📈", "Blue Team", ["Splunk / ELK", "Suricata / Snort", "Sigma rules", "MITRE ATT&CK"]),
    rs("☁️", "Cloud", ["Prowler / ScoutSuite", "CIS Benchmarks", "Cloud IAM", "SC-200 / CySA+"]),
    rs("🎓", "Certs", ["CompTIA Security+", "CySA+", "OSCP (later)", "Azure SC-200"]),
  ],
};

/* ===================== BACKEND ENGINEER ===================== */
const BACKEND_ENGINEER = {
  phases: [
    ph("p1", "Months 1–3", "Foundations", "Language, DS&A, SQL",
      "Build strong programming, algorithm, and database fundamentals.",
      ["(optional) language cert"],
      [
        mo(1, "Language & DS&A",
          ["Pick a language (Node/Python/Go)", "Data structures & algorithms", "Git & testing"],
          ["Solve DS&A problems", "Write unit tests", "Use Git workflows"],
          "DS&A practice repo"),
        mo(2, "Databases & SQL",
          ["Relational modeling", "SQL & indexes", "Transactions & ACID"],
          ["Design a schema", "Write complex queries", "Add indexes & measure"],
          "Database schema + queries"),
        mo(3, "HTTP & REST APIs",
          ["HTTP, status codes, REST", "Request/response lifecycle", "JSON & validation"],
          ["Build a small REST API", "Add input validation", "Write API tests"],
          "First REST API"),
      ]),
    ph("p2", "Months 4–6", "APIs & Data", "Auth, databases, caching",
      "Build robust, secure APIs backed by real data stores.",
      ["(optional) cloud associate"],
      [
        mo(4, "Production APIs",
          ["Auth (JWT/OAuth)", "Error handling & logging", "OpenAPI docs"],
          ["Add authentication", "Document with OpenAPI", "Handle errors gracefully"],
          "Authenticated documented API"),
        mo(5, "Databases Deep",
          ["Advanced indexing & query plans", "NoSQL (MongoDB/Redis)", "Migrations"],
          ["Optimize queries", "Add a NoSQL store", "Run migrations"],
          "Optimized data layer"),
        mo(6, "Caching & Queues",
          ["Redis caching", "Message queues (RabbitMQ/Kafka)", "Async processing"],
          ["Add caching", "Process jobs via a queue", "Measure latency gains"],
          "Cached + queue-backed service"),
      ]),
    ph("p3", "Months 7–9", "Architecture & Cloud", "System design, microservices, deploy",
      "Design scalable services and deploy them to the cloud.",
      ["Cloud associate (optional)"],
      [
        mo(7, "System Design",
          ["Scalability & load balancing", "Caching & CDNs", "Consistency & CAP"],
          ["Design a scalable system", "Diagram the architecture", "Justify trade-offs"],
          "System design doc"),
        mo(8, "Microservices & Docker",
          ["Service boundaries", "Docker & Compose", "Inter-service comms"],
          ["Split a monolith", "Containerize services", "Add service-to-service calls"],
          "Microservices sample"),
        mo(9, "Cloud Deploy & CI/CD",
          ["Cloud compute & managed DBs", "CI/CD pipelines", "Secrets & config"],
          ["Deploy to the cloud", "Automate deploys", "Manage secrets"],
          "Deployed service with CI/CD"),
      ]),
    ph("p4", "Months 10–12", "Scale & Capstone", "Reliability, testing, portfolio",
      "Operate reliable backends and ship a capstone.",
      ["🧩 Backend Engineer job-ready"],
      [
        mo(10, "Scaling & Reliability",
          ["Horizontal scaling", "Load balancing & rate limiting", "Event-driven patterns"],
          ["Scale the service", "Add rate limiting", "Introduce async events"],
          "Scaled, resilient backend"),
        mo(11, "Testing & Observability",
          ["Testing pyramid", "Security (OWASP API)", "Metrics, logs, tracing"],
          ["Add integration tests", "Harden the API", "Instrument observability"],
          "Tested, observable service"),
        mo(12, "Capstone & Interview",
          ["End-to-end product", "System-design interviews", "Portfolio"],
          ["Build a full backend product", "Document architecture", "Practice interviews"],
          "Capstone backend + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundations", "🌱", "Backend Aware", "Language, DS&A & SQL",
      ["DS&A practice", "Database modeling", "First REST API", "Testing basics"]),
    ms("6 Months", "APIs", "🔌", "Junior Backend Eng", "Auth, data & caching",
      ["Authenticated API", "Optimized data layer", "Caching + queues", "2+ projects"]),
    ms("9 Months", "Architecture", "🏗️", "Backend Engineer", "System design & cloud",
      ["System design doc", "Microservices sample", "Cloud deploy + CI/CD", "Docker mastered"]),
    ms("12 Months", "Scale", "🧩", "Backend Engineer", "Reliable backend + capstone",
      ["Scaled resilient service", "Tested & observable", "Capstone product", "Interviewing for backend roles"]),
  ],
  resources: [
    rs("📚", "Learn", ["roadmap.sh/backend", "The Odin Project", "MDN / HTTP docs", "System Design Primer"]),
    rs("🧪", "Practice", ["LeetCode", "Exercism", "Build APIs", "Postman"]),
    rs("🛠️", "Tools", ["Node/Express, FastAPI or Go", "PostgreSQL", "Redis", "Docker"]),
    rs("🏗️", "Design", ["System Design Primer", "ByteByteGo", "Designing Data-Intensive Apps", "OpenAPI"]),
    rs("☁️", "Cloud", ["AWS/Azure/GCP free tier", "GitHub Actions", "Render / Fly.io", "Kubernetes (later)"]),
    rs("🔐", "Security", ["OWASP API Top 10", "JWT / OAuth", "Rate limiting", "Secrets management"]),
  ],
};

/* ===================== CLOUD ARCHITECT — AWS variant ===================== */
const CLOUD_ARCHITECT_AWS = {
  phases: [
    ph("p1", "Months 1–3", "Foundations & Core", "AWS core, IAM & networking",
      "Build AWS fundamentals and turn your background into cloud thinking.",
      ["AWS Cloud Practitioner (CLF-C02)"],
      [
        mo(1, "Cloud, Linux & Networking",
          ["Cloud concepts, Regions & AZs", "AWS accounts & billing", "TCP/IP, DNS, Linux CLI"],
          ["Create an account + billing alarms", "Launch EC2 & host on S3", "Build a VPC with subnets"],
          "GitHub 'aws-labs' repo started"),
        mo(2, "Identity & Governance",
          ["IAM users/roles/policies", "AWS Organizations & SCPs", "Tags, Config, CloudTrail"],
          ["Least-privilege IAM", "Multi-account structure", "Enable CloudTrail + Config"],
          "IAM + governance lab"),
        mo(3, "Compute, Storage & App Hosting",
          ["EC2, Lambda, ECS/EKS", "S3, EBS, EFS", "RDS, DynamoDB"],
          ["Deploy same app 3 ways", "Compare cost & ops", "Write an ADR"],
          "ADR-001: Selecting an AWS compute platform"),
      ]),
    ph("p2", "Months 4–6", "Networking, Reliability & SAA", "VPC, DR & Associate cert",
      "Design networks, add resilience, and pass the Associate exam.",
      ["AWS Solutions Architect – Associate (SAA-C03)"],
      [
        mo(4, "Networking Deep Dive",
          ["VPC, subnets, route tables", "ALB/NLB, Route 53, CloudFront", "VPN, Transit Gateway, PrivateLink"],
          ["Build multi-tier VPC", "Add ALB + Route 53", "Private endpoints + logging"],
          "Capstone 1: secure multi-tier network"),
        mo(5, "Monitoring, Backup & DR",
          ["CloudWatch, X-Ray", "Backup & snapshots", "Multi-AZ, RTO/RPO"],
          ["Add metrics & alarms", "Automate backups", "Test failover"],
          "DR runbook"),
        mo(6, "SAA Consolidation",
          ["Full SAA-C03 domains", "Well-Architected basics", "Practice exams"],
          ["Rebuild labs via CLI + IaC", "Break/fix scenarios", "Score 85%+ on practice"],
          "🎓 Pass SAA-C03"),
      ]),
    ph("p3", "Months 7–9", "Automation & Security", "IaC, CI/CD & security",
      "Codify infrastructure, automate delivery, and harden security.",
      ["AWS SysOps / Developer (optional)"],
      [
        mo(7, "Infrastructure as Code",
          ["Terraform + CloudFormation", "Modules & remote state", "Validation & plan"],
          ["Rebuild network in Terraform", "Create reusable modules", "Manage remote state"],
          "IaC repo"),
        mo(8, "CI/CD & Automation",
          ["CodePipeline / GitHub Actions", "Environments & approvals", "OIDC & secrets"],
          ["Build a deploy pipeline", "Add approvals + tests", "Use OIDC (no static keys)"],
          "CI/CD pipeline"),
        mo(9, "Security & Governance",
          ["IAM deep dive, KMS", "GuardDuty, Security Hub", "Config rules & policy"],
          ["Harden with private endpoints", "Enable threat detection", "Add security policies"],
          "Threat model + hardened env"),
      ]),
    ph("p4", "Months 10–12", "Enterprise & Professional", "Landing zone, FinOps & Pro",
      "Design enterprise architectures and target the Professional cert.",
      ["AWS Solutions Architect – Professional (SAP-C02)"],
      [
        mo(10, "Landing Zone & FinOps",
          ["Control Tower & Organizations", "Multi-account landing zone", "Cost management & FinOps"],
          ["Design a landing zone", "Set budgets & alerts", "Optimize cost"],
          "Capstone 2: enterprise landing zone"),
        mo(11, "SAP & Architecture",
          ["Well-Architected pillars", "Advanced patterns & DR", "Case-study practice"],
          ["Solve SAP case studies", "Design + alternatives", "Trade-off analysis"],
          "🎓 Pass SAP-C02"),
        mo(12, "Capstone & Interview",
          ["Production architecture", "Progressive scale design", "Architect interview prep"],
          ["Build a production capstone", "Full portfolio package", "Practice interviews"],
          "Capstone + portfolio"),
      ]),
  ],
  milestones: [
    ms("3 Months", "Foundation", "🌱", "AWS Aware", "Fundamentals & governance",
      ["CLF-C02 (optional) + repo", "IAM & Organizations", "VPC + compute labs", "ADR-001 written"]),
    ms("6 Months", "SAA", "⚙️", "AWS Associate", "Associate certified",
      ["🎓 SAA-C03 passed", "Multi-tier network capstone", "Monitoring + DR", "IaC basics"]),
    ms("9 Months", "Automation", "🚀", "Cloud/DevOps Engineer", "Automated & secured",
      ["Terraform IaC repo", "CI/CD with OIDC", "Security hardening", "Threat model"]),
    ms("12 Months", "Professional", "🏛️", "AWS Solutions Architect", "Professional + capstone",
      ["🎓 SAP-C02 passed", "Enterprise landing zone", "Production capstone", "Interviewing for architect roles"]),
  ],
  resources: [
    rs("📚", "Learn", ["AWS Skill Builder", "Adrian Cantrill", "AWS Well-Architected", "AWS Docs"]),
    rs("🧪", "Practice", ["AWS free tier", "Tutorials Dojo", "Well-Architected Labs", "Workshops.aws"]),
    rs("🧱", "IaC & DevOps", ["Terraform", "CloudFormation/CDK", "GitHub Actions", "CodePipeline"]),
    rs("🔐", "Security", ["IAM & KMS", "GuardDuty", "Security Hub", "AWS Config"]),
    rs("💰", "Cost", ["Cost Explorer", "Budgets", "Compute Optimizer", "FinOps Framework"]),
    rs("🎓", "Certs", ["CLF-C02", "SAA-C03", "SAP-C02", "Specialty exams"]),
  ],
};

/* ===================== Registry + switcher ===================== */
const ROADMAPS = {
  "cloud-architect": {
    variants: { Azure: ROADMAP_CLOUD_ARCHITECT_AZURE, AWS: CLOUD_ARCHITECT_AWS },
    default: "Azure",
  },
  "ai-engineer": AI_ENGINEER,
  "devops-engineer": DEVOPS_ENGINEER,
  "data-engineer": DATA_ENGINEER,
  "cybersecurity-engineer": CYBER_ENGINEER,
  "backend-engineer": BACKEND_ENGINEER,
};

// Swap the active roadmap (mutates PHASES/MILESTONES/RESOURCES/TRACKER from data.js).
function setActiveRoadmap(goalKey, cloud) {
  const entry = ROADMAPS[goalKey] || ROADMAPS["cloud-architect"];
  const rm = entry.variants ? (entry.variants[cloud] || entry.variants[entry.default]) : entry;
  PHASES = rm.phases;
  MILESTONES = rm.milestones;
  RESOURCES = rm.resources;
  // Keep Azure Cloud Architect on legacy (unprefixed) IDs so existing progress is preserved.
  let prefix = "";
  const isAzureArch = goalKey === "cloud-architect" && (!cloud || cloud === "Azure");
  if (!isAzureArch) prefix = goalKey + (entry.variants ? "-" + (cloud || entry.default) : "") + ":";
  TRACKER = buildTracker(PHASES, prefix);
  return { PHASES, MILESTONES, RESOURCES, TRACKER };
}
